-- V2__curated_and_reference_tables.sql
-- Payer Service configuration and reference data.
--
-- Two kinds of table live here and they are governed differently:
--
--   Reference caches (payer_ref, patient_ref, organization_ref, provider_ref,
--   coverage, patient_condition) are seeded from Synthea and never written by
--   the application at runtime.
--
--   Curated configuration (network_participation, prior_auth_eligible_code,
--   prior_auth_criteria) is hand-authored. Synthea has no equivalent and real
--   criteria sets are commercially licensed.
--
-- Table order matters: parents are created before the tables that reference
-- them, so Flyway can run this as a single transaction.

-- ===========================================================================
-- Reference caches, seeded from Synthea
-- ===========================================================================

-- The payer this deployment represents. One row in phase 1.
CREATE TABLE payer_ref (
       id      UUID         PRIMARY KEY,
       name    VARCHAR(128) NOT NULL,
       address VARCHAR(128),
       city    VARCHAR(64),
       state   VARCHAR(32),
       zip     VARCHAR(16),
       phone   VARCHAR(24)
);

-- From patients.csv, filtered to this payer's covered patients.
CREATE TABLE patient_ref (
     id         UUID        PRIMARY KEY,
     first_name VARCHAR(64) NOT NULL,
     last_name  VARCHAR(64) NOT NULL,
     birthdate  DATE        NOT NULL,
     gender     VARCHAR(8),
     address    VARCHAR(128),
     city       VARCHAR(64),
     state      VARCHAR(32),
     zip        VARCHAR(16)
);

-- From organizations.csv. Provider organizations, not the payer.
CREATE TABLE organization_ref (
      id      UUID         PRIMARY KEY,
      name    VARCHAR(128) NOT NULL,
      address VARCHAR(128),
      city    VARCHAR(64),
      state   VARCHAR(32),
      zip     VARCHAR(16)
);

-- From providers.csv. The ordering physicians.
CREATE TABLE provider_ref (
      id              UUID         PRIMARY KEY,
      organization_id UUID         NOT NULL,
      name            VARCHAR(128) NOT NULL,
      specialty       VARCHAR(64),

      CONSTRAINT fk_provider_organization
          FOREIGN KEY (organization_id) REFERENCES organization_ref (id)
);

-- From payer_transitions.csv. Drives the NOT_COVERED intake check.
CREATE TABLE coverage (
      id         BIGSERIAL   PRIMARY KEY,
      patient_id UUID        NOT NULL,
      payer_id   UUID        NOT NULL,
      start_year INT         NOT NULL,
      end_year   INT         NOT NULL,
      ownership  VARCHAR(16),

      CONSTRAINT fk_coverage_patient FOREIGN KEY (patient_id) REFERENCES patient_ref (id),
      CONSTRAINT fk_coverage_payer   FOREIGN KEY (payer_id)   REFERENCES payer_ref (id),
      CONSTRAINT uq_coverage_span    UNIQUE (patient_id, payer_id, start_year)
);

-- From conditions.csv. Read by the rule engine to evaluate criteria.
-- START and STOP are renamed to onset_date and resolved_date: the domain
-- names belong in the database, not the CSV's names.
CREATE TABLE patient_condition (
       id            BIGSERIAL    PRIMARY KEY,
       patient_id    UUID         NOT NULL,
       encounter_id  UUID,
       code          VARCHAR(32)  NOT NULL,
       description   VARCHAR(256),
       onset_date    DATE         NOT NULL,
       resolved_date DATE,

       CONSTRAINT fk_condition_patient
           FOREIGN KEY (patient_id) REFERENCES patient_ref (id)
);

-- ===========================================================================
-- Curated configuration, hand-authored
-- ===========================================================================

-- Synthea has no concept of a provider network, so this table is generated by
-- the seed script rather than derived. Organizations appearing in this payer's
-- encounters are marked in-network, with a deliberate holdout set marked false
-- so the OUT_OF_NETWORK rejection path is reachable in testing.
CREATE TABLE network_participation (
       payer_id        UUID    NOT NULL,
       organization_id UUID    NOT NULL,
       in_network      BOOLEAN NOT NULL,
       effective_from  DATE    NOT NULL,
       effective_to    DATE,

       CONSTRAINT pk_network_participation PRIMARY KEY (payer_id, organization_id),
       CONSTRAINT fk_network_payer        FOREIGN KEY (payer_id)        REFERENCES payer_ref (id),
       CONSTRAINT fk_network_organization FOREIGN KEY (organization_id) REFERENCES organization_ref (id)
);

-- Which codes require prior authorization at all. A request for a code absent
-- from this table is a client error, not a denial.
CREATE TABLE prior_auth_eligible_code (
      code         VARCHAR(32)    NOT NULL,
      code_type    VARCHAR(16)    NOT NULL,
      description  VARCHAR(256)   NOT NULL,
      typical_cost NUMERIC(12, 2),

      CONSTRAINT pk_eligible_code PRIMARY KEY (code, code_type)
);

-- One criterion per eligible code in phase 1.
--
-- required_condition_code NULL with auto_approve_if_met TRUE would auto-approve
-- unconditionally, which is not a case phase 1 needs. Leave the criterion row
-- out entirely instead: the evaluator escalates with NO_CRITERION_DEFINED.
CREATE TABLE prior_auth_criteria (
     id                      BIGSERIAL    PRIMARY KEY,
     code                    VARCHAR(32)  NOT NULL,
     code_type               VARCHAR(16)  NOT NULL,
     criterion_description   VARCHAR(512) NOT NULL,
     required_condition_code VARCHAR(32),
     auto_approve_if_met     BOOLEAN      NOT NULL DEFAULT TRUE,
     default_validity_days   INT          NOT NULL DEFAULT 90,

     CONSTRAINT fk_criteria_eligible_code
         FOREIGN KEY (code, code_type)
             REFERENCES prior_auth_eligible_code (code, code_type),

     CONSTRAINT uq_criteria_per_code UNIQUE (code, code_type)
);

-- ===========================================================================
-- Indexes
-- ===========================================================================

-- Intake coverage check: is this patient covered by this payer right now.
CREATE INDEX idx_coverage_patient_payer ON coverage (patient_id, payer_id);

-- Rule engine: does this patient have the required condition.
CREATE INDEX idx_condition_patient_code ON patient_condition (patient_id, code);

-- Intake network check walks provider to organization.
CREATE INDEX idx_provider_organization ON provider_ref (organization_id);